### PR TITLE
Revert breaking windows changes

### PR DESCRIPTION
**Pull request by gtzampanakis**
Reverted due to issue #21 .

### CODE REVIEW

**Comment by artart78** [comment]
@davidgfnet can you confirm it works again with this pull request?

**Comment by davidgfnet** [comment]
I'll check later and confirm. Thanks!

**Comment by davidgfnet** [comment]
@artart78 Works great with psplibraries, go ahead and merge it!
Thanks

**Comment by davidgfnet** [comment]
Well as a matter of fact it builds great but I'm experiencing crashes on my app due to libfreetype, I'll dig into it...

**Pull request merged**
