### PR TITLE
Mikmod and sdl_mixer update

### PR DESCRIPTION
**Pull request by carstene1ns**
Large diff, but actually brings it to the same versions psplibraries uses.

### CODE REVIEW

**Comment by dbeef** [comment]
Correct me if I am wrong - `pspdev/psp-ports` stores a copy of libraries' sources with patches already applied.

However, when building toolchain, i.e in case of `SDL_mixer` it seems that original sources are downloaded anyway, and then patch is applied:
https://github.com/pspdev/psplibraries/blob/master/scripts/SDL_mixer.sh
...instead of cloning this repository.

Do I understand correctly?

**Comment by carstene1ns** [comment]
Yes, that is something that we should simplify somewhat and clarify somewhere.
There are multiple things, that bug me about psp-ports repo:
- it is cluttered
- out of sync with psplibraries
- missing documentation (only some README.PSP files in subdirectories)

IMO we should get rid of psp-ports, but we need a way to cleanly generate the patches.
Also, some libraries clone from here directly, which would need conversion to patches first.
psp-ports could be split up like we have gcc, binutils and newlib now. We could have dedicated repos following upstream, with less clutter.

**Comment by carstene1ns** [comment]
The overall plan for me is to convert the psplibraries repo to a collection of pkgbuilds, that can either be packaged locally or distributed by repository.
It does not matter at all, if we use patches or a different source than upstream tarballs for me. However psp-ports in it's current state is not really practicable, as it downloads a lot of bloat around the actual needed files.

**Comment by dbeef** [comment]
> psp-ports could be split up like we have gcc, binutils and newlib now. We could have dedicated repos following upstream, with less clutter.

Definitely agree.

> The overall plan for me is to convert the psplibraries repo to a collection of pkgbuilds, that can either be packaged locally or distributed by repository.

Something like [devkitPro/pacman-packages](https://github.com/devkitPro/pacman-packages)?

**Comment by carstene1ns** [comment]
> > psp-ports could be split up like we have gcc, binutils and newlib now. We could have dedicated repos following upstream, with less clutter.
> 
> Definitely agree.

Okay, so let's split up psp-ports repo in smaller repos following upstream.

> > The overall plan for me is to convert the psplibraries repo to a collection of pkgbuilds, that can either be packaged locally or distributed by repository.
> 
> Something like [devkitPro/pacman-packages](https://github.com/devkitPro/pacman-packages)?

Well, the approach is not new to me, I have been an Arch Linux user for a decade and [building packages](https://aur.archlinux.org/packages/?K=carstene1ns&SeB=m) since 2012.
Actually some of devkitpro's packages are based on former AUR packages by me.

**Pull request merged**
